- hosts: 
  - k3smaster
  tasks:
    - name: "Download .kube/config file from k3smaster and put it at ~/.kube/config.k3smaster"
      fetch: 
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube/config.k3smaster
        flat: yes
    - name: "Replace localhost in ~/.kube/config.k3smaster by k3smaster IP address"
      lineinfile: 
        path: ~/.kube/config.k3smaster
        regexp: '    server: https://localhost:6443'
        line: '    server: https://{{groups["k3smaster"][0]}}:6443'
        backrefs: yes
      delegate_to: localhost