---
- name: "Add systemd k3s startup script"
  template:
    src:  k3s.service.server.j2
    dest: /etc/systemd/system/k3s.service
- name: "Start k3s server"
  systemd:
    name: k3s
    state: started
    enabled: yes
    daemon_reload: yes
- name: "Get token for agent"
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: master_server_token
- name: Get master IP
  shell: ip addr show enp0s1 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1
  register: master_server_ip
- name: "Add K8S Token and Hash to dummy host"
  add_host:
    name: "DUMMYHOST"
    master_server_ip: "{{ master_server_ip }}"
    master_server_token:  "{{ master_server_token }}"